/**
 * The control protocol — how something outside Aevistle asks it to do
 * something. Claude Code is the intended caller; anything that can make an
 * HTTP request or write a file works the same way.
 *
 * Kept in `src/core` because all four participants import it: the HTTP server
 * in the main process, the executor in the renderer, the CLI, and the MCP
 * server under `mcp/`. One definition means an operation cannot be added on
 * one side and misspelled on another.
 *
 * ---------------------------------------------------------------------------
 * Why requests travel through the renderer
 * ---------------------------------------------------------------------------
 * The renderer owns application state; the main process only writes what the
 * renderer hands it, on a 350ms debounce. A control request that edited
 * `state.json` directly would be silently overwritten by the next save. So the
 * main process accepts the request, forwards it to the window, and waits for
 * the answer — which also means every control operation goes through exactly
 * the same reducer, validation and scheduler sync as a click would.
 *
 * ---------------------------------------------------------------------------
 * Security posture
 * ---------------------------------------------------------------------------
 * The server binds 127.0.0.1 and nothing else, requires a bearer token that is
 * regenerated on every launch, and is off until switched on in Settings.
 *
 * `send_now` is gated a second time, behind its own setting. Reading state and
 * scheduling a reminder are recoverable; sending mail as the user, right now,
 * to whoever the caller names, is not — and a token sitting in a file on the
 * same machine is a lower bar than the person at the keyboard.
 */

import type { InboxTag, Recurrence } from './types'

/** Everything a caller may ask for. */
export type ControlOp =
  | 'status'
  | 'list_jobs'
  | 'create_reminder'
  | 'cancel_job'
  | 'toggle_job'
  | 'send_now'
  | 'list_logs'
  | 'list_contacts'
  | 'list_templates'
  | 'list_inbox'

/** Operations that change something rather than just reporting it. */
export const WRITING_OPS: readonly ControlOp[] = [
  'create_reminder',
  'cancel_job',
  'toggle_job',
  'send_now',
]

/** Operations refused unless `allowRemoteSend` is also on. */
export const SENDING_OPS: readonly ControlOp[] = ['send_now']

export interface ControlRequest {
  /** Correlates the reply. Generated by whoever accepted the request. */
  id: string
  op: ControlOp
  params: Record<string, unknown>
  /** How the request arrived, for the activity log. */
  via: 'http' | 'drop' | 'cli'
}

export interface ControlResponse {
  id: string
  ok: boolean
  result?: unknown
  error?: string
}

// ---------------------------------------------------------------------------
// Parameter shapes
//
// Declared rather than inferred so the MCP server can publish a schema that
// matches what the executor actually reads.
// ---------------------------------------------------------------------------

export interface CreateReminderParams {
  to: string[]
  subject: string
  body?: string
  cc?: string[]
  bcc?: string[]
  /** ISO 8601, or `YYYY-MM-DD HH:mm`. Interpreted in the app's local zone. */
  at: string
  /** Omit for a one-off. */
  recurrence?: Recurrence
  /** Defaults to the first configured account. */
  accountId?: string
  /** Shown in the schedule list. Defaults to the subject. */
  name?: string
}

export interface SendNowParams {
  to: string[]
  subject: string
  body?: string
  cc?: string[]
  bcc?: string[]
  accountId?: string
}

export interface ListParams {
  limit?: number
}

export interface ListInboxParams extends ListParams {
  unreadOnly?: boolean
  tag?: InboxTag
}

export interface StatusResult {
  app: string
  version: string
  accounts: number
  jobs: { total: number; armed: number }
  logs: number
  contacts: number
  templates: number
  inbox: { accounts: number; messages: number; unread: number }
  /** False when `send_now` will be refused. */
  sendingAllowed: boolean
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

/**
 * What gets written to `<dataRoot>/control/endpoint.json` when the server is
 * running, so a caller does not have to be told the port. Deleted on shutdown;
 * a stale file is detected by the token no longer being accepted.
 */
export interface ControlEndpoint {
  port: number
  token: string
  /** Absolute path of the drop folder, which works whether or not we are up. */
  dropDir: string
  pid: number
  startedAt: number
}

export const CONTROL_DIR = 'control'
export const ENDPOINT_FILE = 'endpoint.json'
export const DROP_DIR = 'drop'

/**
 * The one path a caller can rely on without being told anything.
 *
 * The endpoint file is also written inside the data folder, but the data
 * folder is user-relocatable — it can be on a second drive or a synced share —
 * so a client that only knew about it would have nothing to look up. `~` is
 * the fixed point, and it is where the project already keeps its signing
 * material, so it is not a new place to know about.
 */
export const HOME_CONTROL_DIR = '.aevistle'

/**
 * Parse the `at` field of a reminder.
 *
 * Deliberately strict about one thing: a bare `YYYY-MM-DD HH:mm` is read as
 * local time, not UTC. `new Date('2026-08-10 09:00')` already does that, but
 * `new Date('2026-08-10T09:00')` does too while `...T09:00Z` does not, and a
 * reminder that fires eight hours out is worse than one that refuses to be
 * created. Anything unparseable is an error, never a silent "now".
 */
export function parseWhen(value: unknown): number {
  if (typeof value === 'number' && Number.isFinite(value)) return value
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error('`at` is required: an ISO timestamp or "YYYY-MM-DD HH:mm"')
  }
  const parsed = Date.parse(value.includes('T') ? value : value.replace(' ', 'T'))
  if (!Number.isFinite(parsed)) {
    throw new Error(`could not read \`at\` as a date: ${JSON.stringify(value)}`)
  }
  return parsed
}
